import type { NextPage } from 'next'
import { useRef } from 'react'
import scrollToComponent from 'react-scroll-to-component-ssr';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import VideoBackground from '../components/VideoBackground/VideoBackground'
import MobileMenu from '../components/MobileMenu/MobileMenu'
import Marquee from "react-fast-marquee";

import arrowDown from '../assets/images/down.svg'
import arrowYellowUp from '../assets/images/arrow_yellow_up.svg'
import arrowYellowDown from '../assets/images/arrow_yellow_down.svg'
import foto from '../assets/images/foto.jpg'
import foto2 from '../assets/images/foto2.jpg'

import news1 from '../assets/noticias/news1.png'
import news2 from '../assets/noticias/news2.jpg'
import news3 from '../assets/noticias/news3.jpg'

import logoFooter from '../assets/images/Logo-footer.svg'

import igBlack from '../assets/images/ig-black.svg'
import lnBlack from '../assets/images/ln-black.svg'

const Home: NextPage = () => {

  const scrollToRef = useRef(null);

  const scrollTo = () => {
    scrollToComponent(scrollToRef.current,{align:'top'})
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileMenu/>
      <main className={styles.main}>
        <div className={styles['title-wrapper']}>
          <div>
            <h1>
            La primera central de <br/>
            medios de influencia  <br/>
            para agencias  <br/>
            y anunciantes.
            </h1>
            <div style={{marginTop:'80px'}} onClick={scrollTo}>
              <Image src={arrowDown}/>
            </div>
          </div>
          <VideoBackground/>
        </div>
        <div ref={scrollToRef} className={styles['second-section']}>
          <div style={{paddingLeft:'16px'}}>
            <Image src={arrowYellowUp}/>
          </div>
        <div style={{paddingLeft:'49px'}}>
            <h2>
            En CLOUT
            </h2>
            <p>
              no creamos <br/>
              estrategias<br/>
              con influenciadores,
            </p>
          </div>
          <div style={{'width':'100vw'}}>
            <Image src={foto} layout='responsive'/>
          </div>
          <div style={{paddingLeft:'49px'}}>
            <h2 style={{'lineHeight':'46.4px'}}>
            creamos <br/>
            estrategias <br/>
            de Influencia.
            </h2>
            
          </div>
          <div style={{paddingRight:'16px', textAlign:'right'}}>
            <Image src={arrowYellowDown}/>
          </div>

          <Marquee gradient={false} style={{'height':'44px', 'marginTop':'40px', 'backgroundColor':'#FFC62F'}}>
          <span style={{'color':'#666666', 'fontWeight':'500', 'fontSize':'17px', 'lineHeight':'28px', 'letterSpacing':'0.4em'}}>En el 2020 la publicidad digital</span>
          <div style={{width:'25vw'}}></div>
          </Marquee>

          <div style={{padding: '0 49px', marginTop:'16px', display:'flex', flexDirection:'column' }}>
            <div>
              <Image src={foto2} layout='responsive'/>
            </div>
            <div style={{'marginTop':'30px'}}>
              <h3>
              Conozca más acerca de 
              la importancia del medio 
              de la influencia digital
              </h3>
            </div>
            <div style={{marginTop:'30px'}}>
              <Image src={arrowDown} style={{'transform':'rotate(-90deg)'}}/>
            </div>
          </div>
          
        </div>
        <div className={styles['third-section']}>
          <div>
            <span style={{'fontWeight':'700','fontSize':'30px','lineHeight':'34px', 'letterSpacing':'0.03em'}}>
            Entérese qué se 
            está hablando en 
            el mundo del influencer 
            marketing
            </span>
          </div>
          <div className={styles.newCard}>
              <div>
                <div>
                  <Image src={news1} layout='responsive'/>
                </div>
                <div className={styles['new-title']}>
                <h3>El nacimiento del medio de la influencia</h3>
                </div>
              </div>
          </div>
          <div className={styles.newCard}>
          <div>
                <div>
                  <Image src={news2} layout='responsive'/>
                </div>
                <div className={styles['new-title']}>
                <h3>El real time no da
                  espera CLOUT ASAP</h3>
                </div>
              </div>
          </div>
          <div className={styles.newCard}>
          <div>
                <div>
                  <Image src={news3} layout='responsive'/>
                </div>
                <div className={styles['new-title']}>
                <h3>Estrategias de influencia
adaptadas al real time.</h3>
                </div>
              </div>
          </div>
        
        </div>
      </main>

      <footer className={styles.foot} style={{'paddingTop': '200px',paddingBottom:'60px'}}>

            <div>
              <Image src={logoFooter}/>
            </div>
            <div style={{'marginTop':'25px'}}>
                <span style={{'fontWeight':'500','fontSize':'13px','lineHeight':'20px','letterSpacing':'0.4em','textTransform':'uppercase'}}>
                  latinoamerica
                </span>
            </div>
            <div style={{'marginTop':'80px', 'display':'flex','flexDirection':'row'}}>
               <div style={{flex:'1','margin':'auto'}}>
                <span style={{'fontWeight':'700','fontSize':'16px','lineHeight':'24px','letterSpacing':'0.1em','textTransform':'uppercase'}}>
                  SíGANOS
                  </span>
               </div>
               <div style={{'display':'flex','width':'90px','justifyContent':'space-between'}}>
                  <a href="linkedin.com">
                    <div style={{'width':'37px','height':"37px"}}>
                      <Image src={lnBlack} layout='responsive'/>
                    </div>
                  </a>
                  <a href="instagram.com">
                    <div style={{'width':'37px','height':"37px"}}>
                      <Image src={igBlack} layout='responsive'/>
                    </div>
                  </a>
               </div>
            </div>
      </footer>
    </div>
  )
}

export default Home
